# Generated by Django 3.2.7 on 2021-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songtitle', models.CharField(max_length=30)),
                ('songwriter', models.CharField(max_length=30)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
