# Generated by Django 3.2.7 on 2021-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recommendation',
            field=models.CharField(choices=[('rain', '비가 오는 날에'), ('sunny', '봄이 느껴지는 날에'), ('christmas', '크리스마스의 기분을 느끼고 싶은 날에'), ('midnight', '조용한 새벽 공기에')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
