# Generated by Django 3.2.7 on 2021-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210914_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
