# Generated by Django 3.2.7 on 2021-09-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('opinion', models.CharField(choices=[('good', '추천해요!'), ('bad', '아쉬워요!')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.comment'),
        ),
    ]
