# Generated by Django 3.2.7 on 2021-09-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210920_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
    ]
