# Generated by Django 3.2.7 on 2021-10-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='icon',
            field=models.CharField(choices=[('cat', '🐈'), ('dog', '🐶'), ('good', '👍🏻'), ('happy', '😁'), ('heart', '💜'), ('cool', '😎')], max_length=30, null=True),
        ),
    ]
